name: Automatic Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@master

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.71.2"

      - name: Build
        run: hugo --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          personal_token: ${{ secrets.TOKEN }}
          #external_repository: temuller/astro-visualization/
          publish_dir: ./docs
          #   keep_files: true
          user_name: temuller
          user_email: <t.e.muller-bravo@soton.ac.uk>
          publish_branch: master
        #   cname: example.com

