name: Automatic Deployment

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.1"

      - name: Build and deploy
        uses: victoriadrake/hugo-latest-cd@master

